services:
  - docker

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    env:
      - ARCH=amd64

before_script:
  - cd archs/$ARCH

script:
  - docker build -t chrmod/snap-irc/$ARCH .
  - docker run -v $(pwd):$(pwd) -w $(pwd) -t chrmod/snap-irc/$ARCH sh -c
    "snapcraft"

after_success:
  - openssl aes-256-cbc
    -K $encrypted_dfdd5052bb7e_key
    -iv $encrypted_dfdd5052bb7e_iv
    -in .snapcraft/travis_snapcraft.cfg
    -out .snapcraft/snapcraft.cfg
    -d

deploy:
  provider: script
  script:
    - cp -r ../../.snapcraft .
    - docker run -v $(pwd):$(pwd) -w $(pwd) -t chrmod/snap-irc/$ARCH sh -c
      "snapcraft push *.snap --release edge --target-arch=${ARCH}"
  skip_cleanup: true
  on:
    branch: master
