FROM chrmod/snapcraft-raspberrypi

RUN  apt-get install -y \
  ca-certificates \
  gettext \
  libaspell-dev:armhf \
  libcurl4-gnutls-dev:armhf \
  libevent-dev:armhf \
  libgcrypt20-dev:armhf \
  libgnutls28-dev:armhf \
  libgpg-error-dev:armhf \
  liblua5.3-dev:armhf \
  libncurses5-dev:armhf \
  libprotobuf-dev:armhf \
  libprotobuf-dev \
  libssl-dev:armhf \
  libv8-dev:armhf \
  openssl \
  zlib1g-dev:armhf
